
import { MenuItem, Category } from './types';

// Data menu diperbarui dengan foto-foto baru yang berfungsi dan berkualitas tinggi.
export const MENU_ITEMS: MenuItem[] = [
  {
    id: '3',
    name: 'Es Teler',
    description: 'Minuman segar dengan isian alpukat, nangka, kelapa muda, dan sirup cocopandan. Juara pelepas dahaga.',
    price: 20000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368394/Es_Teler_vyc2aq.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 10,
    calories: 350
  },
  {
    id: '4',
    name: 'Tahu Gimbal Semarang',
    description: 'Tahu goreng renyah dengan gimbal udang, lontong, tauge, dan siraman bumbu kacang petis yang khas.',
    price: 28000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768287613/Tahu_Gimbal_Semarang_tjtpa0.webp',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.7,
    prepTime: 20,
    calories: 480
  },
  {
    id: '5',
    name: 'Soto Pindang Kudus',
    description: 'Soto khas Kudus dengan kuah bening kaya rempah, suwiran daging sapi pindang, tauge, dan taburan bawang goreng.',
    price: 44454,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368455/Soto_Pindang_Kudus_orwjnb.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 15,
    calories: 420
  },
  {
    id: '6',
    name: 'Soto Ayam Semarang',
    description: 'Soto ayam bening khas Semarang dengan suwiran ayam, soun, tauge, dan taburan koya gurih. Segar dan menghangatkan.',
    price: 20909,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768287616/Soto_Ayam_Semarang_m4xtel.webp',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 15,
    calories: 400
  },
  {
    id: '7',
    name: 'Rawon Semarang',
    description: 'Sup daging sapi khas dengan kuah hitam pekat dari kluwek, disajikan dengan tauge, telur asin, dan sambal terasi.',
    price: 42000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768287617/Rawon_Semarang_vaxfch.webp',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.9,
    prepTime: 20,
    calories: 450
  },
  {
    id: '8',
    name: 'Nasi Goreng Mawut Semarang',
    description: 'Perpaduan unik nasi dan mie goreng khas Semarang, dimasak dengan suwiran ayam, telur, dan sayuran segar.',
    price: 30000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368489/Nasi_Goreng_Mawut_Semarang_zijcjv.png',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.7,
    prepTime: 15,
    calories: 580
  },
  {
    id: '9',
    name: 'Nasi Goreng Jawa',
    description: 'Nasi goreng dengan bumbu medok khas Jawa, menggunakan terasi dan kecap manis, disajikan dengan suwiran ayam kampung dan acar timun.',
    price: 30000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768235951/Nasi_Goreng_Jawa_mqtalj.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 15,
    calories: 600,
    addons: [
      { id: 'ad1', name: 'Telur Ceplok', price: 5000 },
      { id: 'ad2', name: 'Telur Dadar', price: 5000 },
      { id: 'ad3', name: 'Pete', price: 7000 },
      { id: 'ad4', name: 'Extra Kerupuk', price: 3000 }
    ]
  },
  {
    id: '10',
    name: 'Nasi Ayam Lengkuas Semarang',
    description: 'Ayam goreng bumbu lengkuas yang meresap sempurna, disajikan dengan nasi hangat, sambal, dan lalapan segar.',
    price: 30000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368557/Nasi_Ayam_Lengkuas_Semarang_t5tngf.png',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 20,
    calories: 550
  },
  {
    id: '11',
    name: 'Gulai Mangut Semarang',
    description: 'Ikan asap khas Semarang dalam kuah gulai santan pedas yang kaya rempah, disajikan dengan daun kemangi.',
    price: 35000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368591/Gulai_Mangut_Semarang_ks56tv.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.9,
    prepTime: 20,
    calories: 470
  },
  {
    id: '12',
    name: 'Bakmi Goreng Jawa',
    description: 'Bakmi goreng khas Jawa dengan bumbu manis gurih, suwiran ayam, telur orak-arik, dan sayuran segar.',
    price: 29000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368626/Bakmi_Goreng_Jawa_twbo9h.png',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 15,
    calories: 560,
    addons: [
      { id: 'ad5', name: 'Extra Ati Ampela', price: 10000 },
      { id: 'ad6', name: 'Extra Sosis', price: 7000 },
      { id: 'ad7', name: 'Extra Bakso', price: 7000 }
    ]
  },
  {
    id: '13',
    name: 'Bakmi Godog Jawa',
    description: 'Bakmi rebus khas Jawa dengan kuah kaldu ayam gurih, suwiran ayam, sayuran, dan telur. Menghangatkan dan mengenyangkan.',
    price: 32000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368653/Bakmi_Godog_Jawa_pq3ktp.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 15,
    calories: 520
  },
  {
    id: '14',
    name: 'Ayam Goreng Penyet Semarang',
    description: 'Ayam goreng empuk yang dipenyet dan disajikan dengan sambal terasi pedas khas Semarang, lengkap dengan lalapan segar.',
    price: 34000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368686/Ayam_Goreng_Penyet_Semarang_qsbpul.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Makanan',
    rating: 4.8,
    prepTime: 20,
    calories: 550
  },
  {
    id: '15',
    name: 'Teh Poci',
    description: 'Teh tubruk khas Jawa yang disajikan dalam poci tanah liat dengan gula batu, memberikan aroma dan rasa otentik.',
    price: 25000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768367917/Jus_Strawberry_yqxwqr.jpg',
    isAvailable: true,
    isFavorite: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 7,
    calories: 80
  },
  {
    id: '16',
    name: 'Teh Pucuk',
    description: 'Teh kemasan favorit yang menyegarkan, dibuat dari pucuk daun teh pilihan.',
    price: 5000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768367756/Teh_Pucuk_cyylsu.png',
    isAvailable: true,
    isFavorite: false,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 2,
    calories: 60
  },
  {
    id: '17',
    name: 'Pulpy Orange',
    description: 'Minuman jeruk menyegarkan dengan sensasi bulir jeruk asli, manis pas dan kaya vitamin C.',
    price: 8500,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768370346/Pulpy_Orange_wckhxi.png',
    isAvailable: true,
    isFavorite: false,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 5,
    calories: 140
  },
  {
    id: '18',
    name: 'Lemon Tea',
    description: 'Perpaduan klasik teh berkualitas dengan perasan lemon segar, memberikan sensasi asam manis yang menyegarkan.',
    price: 15000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368807/Lemon_Tea_f0eewa.png',
    isAvailable: true,
    isFavorite: false,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 5,
    calories: 70
  },
  {
    id: '19',
    name: 'Jus Strawberry',
    description: 'Jus strawberry segar dibuat dari buah asli, manis dan kaya vitamin.',
    price: 25000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768367917/Jus_Strawberry_yqxwqr.jpg',
    isAvailable: true,
    isFavorite: false,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 150
  },
  {
    id: '20',
    name: 'Jus Semangka',
    description: 'Jus semangka murni tanpa tambahan gula, pilihan sehat dan menyegarkan di cuaca panas.',
    price: 25000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768367950/Jus_Semangka_if4iit.jpg',
    isAvailable: true,
    isFavorite: false,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 130
  },
  {
    id: '21',
    name: 'Jus Buah Naga',
    description: 'Jus buah naga segar yang kaya antioksidan, disajikan dingin untuk menemani santap Anda.',
    price: 25000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768367988/Jus_Buah_Naga_fcginv.jpg',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 140
  },
  {
    id: '22',
    name: 'Jus Belimbing',
    description: 'Jus belimbing segar yang kaya vitamin C, pilihan sehat untuk menemani hari Anda.',
    price: 25000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368066/Jus_Belimbing_i7fyph.jpg',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 120
  },
  {
    id: '23',
    name: 'Jeruk Peras',
    description: 'Es jeruk peras murni dari buah jeruk segar, kaya vitamin C dan menyegarkan.',
    price: 20000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368103/Jeruk_Peras_brx7it.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 110
  },
  {
    id: '24',
    name: 'Green Tea',
    description: 'Teh hijau berkualitas yang menenangkan, disajikan hangat atau dingin sesuai selera.',
    price: 15000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368141/Green_Tea_lpxl27.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 5,
    calories: 80
  },
  {
    id: '25',
    name: 'Aneka Soda',
    description: 'Pilihan soda favorit untuk menyegarkan harimu. Pilih antara Fanta, Sprite, atau Coca-Cola.',
    price: 7000,
    imageUrl: 'https://zyalxogxdxeoisuwwmic.supabase.co/storage/v1/object/public/public-images/Sprite,%20Fanta,%20Coca-cola.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 2,
    calories: 150
  },
  {
    id: '26',
    name: 'Es Teh',
    description: 'Teh tawar segar yang disajikan dingin, pilihan klasik untuk melegakan dahaga.',
    price: 9000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368229/Es_Teh_yxd52v.jpg',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.6,
    prepTime: 3,
    calories: 5
  },
  {
    id: '27',
    name: 'Es Soda Gembira',
    description: 'Minuman soda klasik dengan susu kental manis dan sirup frambozen, menyegarkan dan membangkitkan nostalgia.',
    price: 18500,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368263/Es_Soda_Gembira_vurlli.jpg',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.7,
    prepTime: 5,
    calories: 200
  },
  {
    id: '28',
    name: 'Cleo',
    description: 'Air mineral murni untuk menemani setiap hidangan Anda, menjaga kesegaran tubuh.',
    price: 3000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368297/Cleo_ozckuq.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.6,
    prepTime: 2,
    calories: 0
  },
  {
    id: '29',
    name: 'Roti Bakar Keju Karamel',
    description: 'Roti bakar renyah dengan topping keju melimpah dan siraman saus karamel manis legit. Cocok untuk teman ngopi.',
    price: 22000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368766/Roti_Bakar_Keju_Karamel_ivy0yr.jpg',
    isAvailable: true,
    isFavorite: true,
    isNew: true,
    category: 'Snack',
    rating: 4.8,
    prepTime: 10,
    calories: 380
  },
  {
    id: '30',
    name: 'Pisang Goreng Keju Karamel',
    description: 'Pisang kepok kuning pilihan digoreng renyah, bertabur keju parut melimpah dan saus karamel legit.',
    price: 20000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368743/Pisang_Goreng_Keju_Karamel_lqjxrw.png',
    isAvailable: true,
    isFavorite: true,
    isNew: true,
    category: 'Snack',
    rating: 4.8,
    prepTime: 12,
    calories: 320
  },
  {
    id: '31',
    name: 'Nipis Madu',
    description: 'Perpaduan segar jeruk nipis dan manisnya madu alami, disajikan dingin untuk melepas dahaga.',
    price: 7000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768370018/Nipis_Madu_saf8bz.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 5,
    calories: 100
  },
  {
    id: '32',
    name: 'Aqua',
    description: 'Air mineral berkualitas dari sumber mata air pegunungan terpilih. Segar dan alami.',
    price: 6000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768368328/Aqua_ggoxcp.png',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Minuman',
    rating: 4.8,
    prepTime: 2,
    calories: 0
  },
  {
    id: '33',
    name: 'Emping',
    description: 'Emping melinjo renyah dan gurih, pelengkap sempurna untuk soto dan masakan berkuah lainnya.',
    price: 6000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768394165/emping_e3vnp5.webp',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Snack',
    rating: 4.6,
    prepTime: 1,
    calories: 180
  },
  {
    id: '34',
    name: 'Kerupuk Udang',
    description: 'Kerupuk udang premium yang digoreng garing. Renyah, gurih, dan terasa udangnya.',
    price: 6000,
    imageUrl: 'https://res.cloudinary.com/dwdaydzsh/image/upload/v1768394245/shrimp-crackers_bjwpba.jpg',
    isAvailable: true,
    isFavorite: false,
    isNew: true,
    category: 'Snack',
    rating: 4.7,
    prepTime: 1,
    calories: 150
  }
];

// Kategori disederhanakan untuk mencocokkan data menu yang baru.
export const CATEGORIES: Category[] = [
  'Terlaris', 
  'Menu Baru',
  'Makanan',
  'Minuman',
  'Snack'
];
